# Generated by Django 3.1.7 on 2021-03-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210320_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Наличие SD карты'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_value_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Встроенная память'),
        ),
    ]
